// cmd/export.go
package cmd

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/jpequegn/xmon/internal/account"
	"github.com/jpequegn/xmon/internal/analysis"
	"github.com/jpequegn/xmon/internal/config"
	"github.com/jpequegn/xmon/internal/database"
	"github.com/jpequegn/xmon/internal/tweet"
	"github.com/spf13/cobra"
)

var exportCmd = &cobra.Command{
	Use:   "export",
	Short: "Generate markdown report",
	Long:  `Exports activity digest as markdown for sharing or archiving.`,
	RunE:  runExport,
}

var (
	exportDays int
)

func init() {
	rootCmd.AddCommand(exportCmd)
	exportCmd.Flags().IntVar(&exportDays, "days", 7, "Number of days to include in export")
}

func runExport(cmd *cobra.Command, args []string) error {
	db, err := database.New(config.DBPath())
	if err != nil {
		return fmt.Errorf("failed to open database: %w", err)
	}
	defer db.Close()

	since := time.Now().AddDate(0, 0, -exportDays)
	endDate := time.Now()

	accountRepo := account.NewRepository(db)
	tweetRepo := tweet.NewRepository(db)

	accounts, _ := accountRepo.List()
	accountMap := make(map[int64]*account.Account)
	for i := range accounts {
		accountMap[accounts[i].ID] = &accounts[i]
	}

	originals, retweets, quotes, _ := tweetRepo.CountByType(since)
	totalTweets := originals + retweets + quotes
	tweets, _ := tweetRepo.GetSince(since)

	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("# X Activity Digest\n\n"))
	sb.WriteString(fmt.Sprintf("**Period:** %s - %s\n\n",
		since.Format("January 2, 2006"),
		endDate.Format("January 2, 2006")))

	// Summary
	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Accounts monitored:** %d\n", len(accounts)))
	sb.WriteString(fmt.Sprintf("- **Total tweets:** %d\n", totalTweets))
	sb.WriteString(fmt.Sprintf("- **Original tweets:** %d\n", originals))
	sb.WriteString(fmt.Sprintf("- **Retweets:** %d\n", retweets))
	sb.WriteString(fmt.Sprintf("- **Quote tweets:** %d\n\n", quotes))

	// Most Active
	if len(tweets) > 0 {
		sb.WriteString("## Most Active\n\n")
		sb.WriteString("| Account | Tweets |\n")
		sb.WriteString("|---------|-------:|\n")

		tweetCounts := make(map[int64]int)
		for _, t := range tweets {
			tweetCounts[t.AccountID]++
		}

		type accountTweets struct {
			username string
			count    int
		}
		var sorted []accountTweets
		for accID, count := range tweetCounts {
			if acc, ok := accountMap[accID]; ok {
				sorted = append(sorted, accountTweets{acc.Username, count})
			}
		}
		sort.Slice(sorted, func(i, j int) bool {
			return sorted[i].count > sorted[j].count
		})

		limit := 10
		if len(sorted) < limit {
			limit = len(sorted)
		}
		for i := 0; i < limit; i++ {
			sb.WriteString(fmt.Sprintf("| [@%s](https://x.com/%s) | %d |\n",
				sorted[i].username, sorted[i].username, sorted[i].count))
		}
		sb.WriteString("\n")
	}

	// Most Amplified
	amplifiedUsers, _ := tweetRepo.GetAmplifiedWithSources(since, 2)
	if len(amplifiedUsers) > 0 {
		sb.WriteString("## Most Amplified (retweeted by multiple follows)\n\n")
		for _, a := range amplifiedUsers {
			sb.WriteString(fmt.Sprintf("- [@%s](https://x.com/%s) - amplified by %s\n",
				a.Username, a.Username, strings.Join(a.AmplifiedBy, ", ")))
		}
		sb.WriteString("\n")
	}

	// Trending Topics
	var tweetContents []string
	for _, t := range tweets {
		if t.Content != "" {
			tweetContents = append(tweetContents, t.Content)
		}
	}
	topics := analysis.ExtractTopics(tweetContents, 10)
	if len(topics) > 0 {
		sb.WriteString("## Trending Topics\n\n")
		sb.WriteString(strings.Join(topics, " · "))
		sb.WriteString("\n\n")
	}

	// Notable Tweets
	topTweets, _ := tweetRepo.GetTopTweets(since, 5)
	if len(topTweets) > 0 {
		sb.WriteString("## Notable Tweets\n\n")
		for _, t := range topTweets {
			if acc, ok := accountMap[t.AccountID]; ok {
				content := t.Content
				if len(content) > 200 {
					content = content[:197] + "..."
				}
				// Escape any markdown in content
				content = strings.ReplaceAll(content, "\n", " ")
				sb.WriteString(fmt.Sprintf("**@%s**: %s\n", acc.Username, content))
				sb.WriteString(fmt.Sprintf("> %d likes · %d RTs\n\n", t.Likes, t.Retweets))
			}
		}
	}

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString(fmt.Sprintf("*Generated by [xmon](https://github.com/jpequegn/xmon) on %s*\n",
		time.Now().Format("2006-01-02 15:04")))

	fmt.Print(sb.String())
	return nil
}
